---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie
  template:
    metadata:
      labels:
        app: movie
    spec:
      containers:
      - name: metadata
        image: microservice-go/movie
        imagePullPolicy: Never
        ports:
          - containerPort: 8083